export const GET_PERSON_DETAILS_REQUEST = 'GET_PERSON_DETAILS_REQUEST';
export const GET_PERSON_DETAILS_SUCCESS = 'GET_PERSON_DETAILS_SUCCESS';
export const GET_PERSON_DETAILS_ERROR = 'GET_PERSON_DETAILS_ERROR';
export const GET_PERSON_DETAILS = 'GET_PERSON_DETAILS';
